CREATE DATABASE IF NOT EXISTS todolist;
USE todolist;

CREATE TABLE IF NOT EXISTS Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(191) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS RefreshTokens(
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IdUser INT NOT NULL,
    RefreshToken CHAR(64) NOT NULL UNIQUE,
    ExpiresAt DATETIME NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Revoked BOOLEAN NOT NULL DEFAULT FALSE,
    
    CONSTRAINT fkIdUsers FOREIGN KEY (IdUser) REFERENCES Users(Id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS Tasks (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description VARCHAR(300) NOT NULL DEFAULT "",
    Date DATE NOT NULL,
    Time TIME NOT NULL,
    State ENUM('To do', 'Done') NOT NULL DEFAULT 'To do',
    IdUser INT NOT NULL,
    FOREIGN KEY (IdUser) REFERENCES Users(Id) ON DELETE CASCADE
);